config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get '/about' => 'landing#about'
  get '/story' => 'landing#story'
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class IssueComment < Application::Base
  belongs_to :issue
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  validates :github_identifier, uniqueness: true

  belongs_to :user
  belongs_to :repository

  # NOTE: if data gets big enough we may want to paritition commits into multiple commits by day tables
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |commit|
        csv << commit.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :repository

  has_many :issue_comments

  validates :issue_number, uniqueness: { scope: [:repository_id] }
end

app/models/issue_comment.rb
class IssueComment < ActiveRecord::Base
  belongs_to :issue
  belongs_to :user
end

app/models/matviews/chattiest_user.rb
module Matviews::ChattiestUser
  class Last0 < Matviews::Matview
    self.table_name = "chattiest_users_matview_last_0"
  end

  class Last7 < Matviews::Matview
    self.table_name = "chattiest_users_matview_last_7"
  end

  class Last30 < Matviews::Matview
    self.table_name = "chattiest_users_matview_last_30"
  end

  class Last90 < Matviews::Matview
    self.table_name = "chattiest_users_matview_last_90"
  end
end

app/models/matviews/issue_activity.rb
module Matviews::IssueActivity
  class Last0 < Matviews::Matview
    self.table_name = "issue_activity_matview_last_0"
  end

  class Last7 < Matviews::Matview
    self.table_name = "issue_activity_matview_last_7"
  end

  class Last30 < Matviews::Matview
    self.table_name = "issue_activity_matview_last_30"
  end

  class Last90 < Matviews::Matview
    self.table_name = "issue_activity_matview_last_90"
  end
end

app/models/matviews/matview.rb
class Matviews::Matview < ActiveRecord::Base
  def self.refresh
    puts "Attempting to refresh: #{self.table_name}"
    ActiveRecord::Base.connection.execute("REFRESH MATERIALIZED VIEW #{self.table_name}")
    puts "#{self.table_name} refreshed"
  end

  def readonly?
    true
  end
end

app/models/matviews/repo_activity.rb
module Matviews::RepoActivity
  class Last0 < Matviews::Matview
    self.table_name = "repo_activity_matview_last_0"
  end

  class Last7 < Matviews::Matview
    self.table_name = "repo_activity_matview_last_7"
  end

  class Last30 < Matviews::Matview
    self.table_name = "repo_activity_matview_last_30"
  end

  class Last90 < Matviews::Matview
    self.table_name = "repo_activity_matview_last_90"
  end
end

app/models/matviews/top_user.rb
module Matviews::TopUser
  class Last0 < Matviews::Matview
    self.table_name = "top_users_matview_last_0"
  end

  class Last7 < Matviews::Matview
    self.table_name = "top_users_matview_last_7"
  end

  class Last30 < Matviews::Matview
    self.table_name = "top_users_matview_last_30"
  end

  class Last90 < Matviews::Matview
    self.table_name = "top_users_matview_last_90"
  end
end

app/models/repo_activity_matview_last_90.rb
class RepoActivityMatviewLast90 < ActiveRecord::Base
  self.table_name = "repo_activity_matview_last_90"

  def self.refresh
    ActiveRecord::Base.connection.execute('REFRESH MATERIALIZED VIEW repo_activity_matview_last_90')
  end

  def readonly?
    true
  end
end

app/models/repository.rb
# TODO: There eventually needs to be a callback here to add a Repository to the
#       Redis queue on creation
class Repository < ActiveRecord::Base
  include Comparable

  validates :github_id, uniqueness: true, on: :create
  attr_readonly :github_id

  has_many :commits
  has_many :issues

  def update_score
    update(score: calculate_score)
  end

  def calculate_score
    activity_score + significance_score
  end

  def <=>(other)
    score <=> other.score
  end

  private

  def activity_score
    # TODO: We should only get the commits for a given time period, when calculating
    # this, not all the commits on a repository.Should we add scoring for issues
    # based on comments activity?
    commits.count + open_issues.to_i
  end

  def significance_score
    # convert any nil values to zero with to_i
    stars.to_i + forks.to_i + watchers.to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # TODO: User is the wrong name. This should be github_accounts, open_sourcerers, or developers,
  # but not user. We will probably want to have a user for our app eventually that
  # is separate from github user account info.
  validates :github_username, uniqueness: true

  has_many :commits
  has_many :issue_comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :set_activity_vars

  def index
    respond_to do |type|
      type.html
      type.js do
          render partial: 'landing/index.js.erb'
      end
    end
  end

  def about; end

  def story; end

  private

  def set_activity_vars
    postfix = date_range_postfix
    @repos = Module.const_get("Matviews::RepoActivity::#{postfix}").limit(10)
    @committers = Module.const_get("Matviews::TopUser::#{postfix}").limit(10)
    @issues = Module.const_get("Matviews::IssueActivity::#{postfix}").limit(10)
    @chatties = Module.const_get("Matviews::ChattiestUser::#{postfix}").limit(10)
  end

  def date_range_postfix
    case params['date_range']
    when 'today'
      'Last0'
    when 'weekly'
      'Last7'
    when 'monthly'
      'Last30'
    when 'last 90'
      'Last90'
    else
      'Last0'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_table_partial(collection, partial_path)
    if collection.empty?
      "errors/no_data"
    else
      partial_path
    end
  end
end

app/views/chatties/_index.html.erb
<% @chatties.each_with_index do |user, i| %>
<tr>
  <td><%= i + 1 %></td>
  <% username = user.github_username %>
  <td><%= link_to username, "https://github.com/#{username}" %></td>
  <td><%= user.hit_count %></td>
</tr>
<% end %>

app/views/committers/_index.html.erb
<% @committers.each_with_index do |committer, i| %>
<tr>
  <td><%= i + 1 %></td>
  <% username = committer.github_username %>
  <td><%= link_to username, "https://github.com/#{username}" %></td>
  <td><%= committer.hit_count %></td>
</tr>
<% end %>

app/views/issues/_index.html.erb
<% @issues.each_with_index do |issue, i| %>
<tr>
  <td><%= i + 1 %></td>
  <td>
    <%= link_to issue.repository_name, issue.repository_url %><!-- 
    --><%= link_to "##{issue.issue_number}", "https://github.com#{issue.url}" %>
  </td>
  <td><%= issue.hit_count %></td>
</tr>
<% end %>

app/views/landing/_index.js.erb
(function rerenderActivities() {
  $("table#repositories tbody").html("<%= j render(set_table_partial(@repos, 'repositories/index'))%>").html_safe;
  $("table#committers tbody").html("<%= j render(set_table_partial(@committers, 'committers/index')) %>").html_safe
  $("table#issues tbody").html("<%= j render(set_table_partial(@issues,'issues/index')) %>").html_safe
  $("table#chatties tbody").html("<%= j render(set_table_partial(@chatties, 'chatties/index')) %>").html_safe
})();

app/views/landing/about.html.erb
<% require 'digest' %>
<main class="about">
  <h1 class="about center-align" id="about-header">Who We Are</h1>

  <% lukas = { name: 'Lukas Nimmo', url: 'http://numbluk.com', email: 'Lukas.Nimmo@gmail.com'} %>
  <% michael = { name: 'Michael Mentele', url: 'http://getmichaelonboard.com', email: 'michaelrmentele@gmail.com' } %>
  <% names = [ lukas, michael ] %>

  <div class="row about" id="bios">
    <% names.shuffle.each_with_index do |name, i| %>
    <a class="center-align" href="<%= name[:url] %>">
      <div class="col s6 m4 l3 bio <%= 'offset-m2 offset-l3' if i == 0 %>">
        <div class="col s12">
          <% email = name[:email].downcase %>
          <% sha = Digest::MD5.hexdigest(email) %>
          <img class="circle responsive-img" src="https://www.gravatar.com/avatar/<%= sha %>?s=800">
        </div>
        <h2><%= name[:name] %></h2>
      </a>
    </div>
    <% end %>
  </div>

  
  <%= render 'shared/footer' %>
</div>

app/views/landing/index.html.erb
<main>
  <div class="row description">
    <div class="col s12 m8 l6 offset-l3 offset-m2">
        <p class="flow-text" id="description">
          OpenSource Watch is up to date with everything that is going on in the 100,000 most popular open source libraries on Github. Easily check the top activity among libraries, issues, and developers up to the last 90 days. We are growing fast so keep watching!
        </p>
      </div>
  </div>

  <div class="row pushpin-date-range-row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
      <ul class="tabs tabs-fixed-width">
        <li class="tab col s3 m2 l2"><a class='daily' href="#">Daily</a></li>
        <li class="tab col s3 m2 l2"><a class='weekly' href="#">Weekly</a></li>
        <li class="tab col s3 m2 l2"><a class='monthly' href="#">Monthly</a></li>
        <li class="tab col s3 m2 l2"><a class='last90' href="#">Last 90</a></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m5 l5 hoverable">
      <table class="bordered highlight centered" id="repositories">
        <h4 class="center-align">Top Repositories</h3>
        <thead>
          <tr>
            <th>Rank</th>
            <th>Repository</th>
            <th>Commits</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'repositories/index' %>
        </tbody>
      </table>
    </div>

    <div class="col s12 m5 l5 hoverable">
      <table class="bordered highlight centered" id="committers">
        <h4 class="center-align">Top Committers</h3>
        <thead>
          <tr>
            <th>Rank</th>
            <th>Commiter</th>
            <th>Commits</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'committers/index' %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m5 l5 hoverable">
      <table class="bordered highlight centered" id="issues">
        <h4 class="center-align">Active Issues</h3>
        <thead>
          <tr>
            <th>Rank</th>
            <th>Repository#Issue</th>
            <th>Comments</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'issues/index' %>
        </tbody>
      </table>
    </div>

    <div class="col s12 m5 l5 hoverable">
      <table class="bordered highlight centered" id="chatties">
        <h4 class="center-align">Chattiest Users</h3>
        <thead>
          <tr>
            <th>Rank</th>
            <th>User</th>
            <th>Comments</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'chatties/index' %>
        </tbody>
      </table>
    </div>
  </div>
</main>

<%= render 'shared/footer' %>

app/views/landing/story.html.erb
<div class="row story">
  <div class="col s10 offset-s1 m10 offset-m1 l8 offset-l2">
    <%= render 'landing/article' %>
  <!-- Row and colum end -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open Source Watch</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render "shared/messages" %>
    <%= yield %>
  </body>
</html>

app/views/repositories/_index.html.erb
<% @repos.each_with_index do |repo, i| %>
<tr>
  <td><%= i + 1 %></td>
  <% url = repo.url %>
  <% group_and_name = /github.com\/(.*)/.match(url)[1] %>
  <td><%= link_to group_and_name, url %></td>
  <td><%= repo.hit_count %></td>
</tr>
<% end %>

app/views/ruby_gems/index.html.erb
<%= form_tag(ruby_gems_search_path, method: "get") do %>
  <%= label_tag(:search, "Search for Gem:") %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>

<ul>
  <% if @search_results %>
    <% @search_results.each do |result| %>
      <li>
        <h3><%= result[:name].html_safe %></h3>
        <p><%= result[:description].html_safe %></p>
      </li>
    <% end %>
  <% elsif @gems %>
    <% @gems.each_with_index do |gem, idx| %>
      <li>
        <span><%= idx + 1 %></span>
        <h3><%= gem.name %></h3>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col s12">
    &copy; 2017 OpenSource Watch
    <%#<a class="grey-text text-lighten-4 right" href="#!">Email Us</a>%>
  </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <%= link_to root_path, class: "brand-logo center" do %>
        <%= image_tag("logo-opensourcewatch-white.png", id: 'logo') %>
        <span>pen Source Watch</span>
      <% end %>
      <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up"><%= fa_icon 'bars' %></a>
      <ul class="right hide-on-small-and-down">
        <li><%= link_to 'Story', story_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Story', story_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_messages.html.erb
<% # danger, info, warning, success %>
<% flash.each do |type, msg| %>
  <div class="alert alert-#{type}">
    <a class="close" date-dismiss='alert'> &#215;
    <%= content_tag :div, msg, id: "flash_#{type}" if msg.is_a?(String) %>
<% end %>